// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCucO-CBcTvZQhLrBzrlEnhaRqTT0wZuwI',
    appId: '1:774618353237:web:b86f6f4ff76885e4084edc',
    messagingSenderId: '774618353237',
    projectId: 'al-madina-traders',
    authDomain: 'al-madina-traders.firebaseapp.com',
    storageBucket: 'al-madina-traders.appspot.com',
    measurementId: 'G-DFWV11PHDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoH-ikD836hUemWWizGbicYZ5MWwEQ5Xc',
    appId: '1:774618353237:android:ee8cffd29f96160f084edc',
    messagingSenderId: '774618353237',
    projectId: 'al-madina-traders',
    storageBucket: 'al-madina-traders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClnOCGgmvWoPcZnaiZRxX-DeT040DbwT4',
    appId: '1:774618353237:ios:ebe4be7a69704870084edc',
    messagingSenderId: '774618353237',
    projectId: 'al-madina-traders',
    storageBucket: 'al-madina-traders.appspot.com',
    iosBundleId: 'com.becoder.alMadinaTraders',
  );
}
